language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 2.0.0
      mono: none
    - os: osx
      osx_image: xcode7.3
      dotnet: 2.0.0
      mono: none

branches:
  only:
  - master
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
script:
  - dotnet test -c Release test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.TestsCore.csproj
