dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
branches:
  only:
  - master
install:
  - dotnet restore castle.core.asyncinterceptor.core.sln
script:
  - dotnet test -f netcoreapp1.1 test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.TestsCore.csproj
