language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 2.0.0
      mono: none
    - os: osx
      dotnet: 2.0.0
      mono: none

branches:
  only:
  - master
script:
  - dotnet test -c Release -f netcoreapp2.0 test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.Tests.csproj
